### ISSUE TITLE
distances and connectivities

### ISSUE THREAD

**Issue by mapourmaleki** [ElementoLab/utag#5]
Hi,
How are distances and connectivities calculated?
I see a lot of 0 distances in the UTUC data and a range of 0 to ~4 with a connectivity of 1. How do you have a distance of 0 and connectivity of 1? We do not see any repeat x, y cell coordinates. 
How does this distance range relate to your max_dist of 20? I would have expected to see distances between 4-20 as well.
Thanks,
Maryam

**Comment by jkim810** [comment]
Hello Maryam,
I see that these distance/connectivity could be misleading. Those features stored in `obsp` are not from spatial coordinates, but rather products of sc.pp.neighbors. It has nothing to do with the "spatial graph" used in UTAG. In the UTUC data, we neither provide the spatial distances nor the connectivity because the `AnnData` object contains multiple regions of interests.
Best,
Junbum Kim
